import type { StandardPlan, UnlimitedCard } from "./types"

export const STANDARD_PLANS: StandardPlan[] = [
  {
    id: "free",
    name: "体验版",
    price: 0,
    points: 0,
    features: ["基础AI辅助", "每日签到领点"],
    theme: "gray",
    cta: "免费开始",
  },
  {
    id: "gold",
    name: "黄金会员",
    price: { monthly: 49, quarterly: 139, yearly: 499 },
    points: 6000,
    features: ["每月获赠6000灵感点", "优先响应队列", "专属客服通道"],
    theme: "cyan",
    cta: "立即订阅",
  },
  {
    id: "platinum",
    name: "铂金会员",
    price: { monthly: 89, quarterly: 259, yearly: 899 },
    points: 13100,
    features: ["每月获赠13100灵感点", "极速生成模式", "长篇记忆上下文"],
    theme: "blue",
    highlight: true,
    cta: "超值推荐",
  },
  {
    id: "black",
    name: "黑金会员",
    price: { monthly: 169, quarterly: 499, yearly: 1699 },
    points: 26700,
    features: ["每月获赠26700灵感点", "独家模型微调", "私有知识库"],
    theme: "black",
    cta: "尊享开通",
  },
]

export const UNLIMITED_CARDS: UnlimitedCard[] = [
  {
    duration: "1日",
    type: "无限体验",
    price: "14.9",
    unit: "天",
    oldPrice: "19.9",
    tag: null,
    desc: "短期冲刺·灵感爆发",
  },
  {
    duration: "3日",
    type: "无限畅想",
    price: "39.0",
    unit: "天",
    oldPrice: "45.0",
    tag: null,
    desc: "周末闭关·码字必备",
  },
  {
    duration: "7日",
    type: "无限周卡",
    price: "59.0",
    unit: "天",
    oldPrice: "99.0",
    tag: "热销",
    desc: "黄金周期·连续创作",
  },
  {
    duration: "月卡",
    type: "无限月卡",
    price: "215",
    unit: "月",
    oldPrice: "299",
    tag: "限时",
    desc: "职业作家·首选方案",
  },
  {
    duration: "季卡",
    type: "无限季卡",
    price: "599",
    unit: "季",
    oldPrice: "799",
    tag: "限时",
    desc: "稳定连载·无视消耗",
  },
  {
    duration: "年卡",
    type: "无限年卡",
    price: "1999",
    unit: "年",
    oldPrice: "2499",
    tag: "双11特惠",
    desc: "工作室·团队力荐",
  },
]
